<?php
//Styles
function my_theme_enqueue_styles()
{
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
}
add_action('wp_enqueue_scripts', 'my_theme_enqueue_styles');

// ACF - Mention légales
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_629f137398eb4',
    'title' => 'Mentions légales',
    'fields' => array(
      array(
        'key' => 'field_629f13853e031',
        'label' => 'URL du site',
        'name' => 'url_du_site',
        'type' => 'text',
        'instructions' => 'URL du site avec https / www',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f1db2f3cd7',
        'label' => 'Nom commercial',
        'name' => 'nom_commercial',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Centre Gilamon',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f13bc3e032',
        'label' => 'Propriétaire',
        'name' => 'proprietaire',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'SC Centre de soins Gilamon Blanquefort Capital social de 153000 € Numéro de TVA: FR52440531010',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f1c6cefdc7',
        'label' => 'Adresse du siège social',
        'name' => 'adresse_siege_social',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '69 rue de Gilamon 33290 Blanquefort',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f13db3e033',
        'label' => 'Responsable publication',
        'name' => 'responsable_publication',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Laplace Jean-Marc – contact@beecommunication.fr',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f13e43e034',
        'label' => 'Webmaster',
        'name' => 'webmaster',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Beecom’ – contact@beecommunication.fr',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f13e73e035',
        'label' => 'Hébergeur',
        'name' => 'hebergeur',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'o2switch – 222 Bd Gustave Flaubert, 63000, Clermont-Ferrand' => 'o2switch – 222 Bd Gustave Flaubert, 63000, Clermont-Ferrand',
          'OVH – 2 rue Kellermann, 59100, Roubaix 1007' => 'OVH – 2 rue Kellermann, 59100, Roubaix 1007',
          'bullWeb.fr – 5, rue Eugène Labiche, 33700, Mérignac' => 'bullWeb.fr – 5, rue Eugène Labiche, 33700, Mérignac',
        ),
        'default_value' => false,
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_629f13eb3e036',
        'label' => 'Délégué à la protection des données (DPO)',
        'name' => 'delegue',
        'type' => 'text',
        'instructions' => 'Ex : Clémence Boucaud',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f1b7f1011f',
        'label' => 'Types de données collectées',
        'name' => 'types_de_donnees',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'Nom, Prénom, adresse e-mail et numéro de téléphone' => 'Nom, Prénom, adresse e-mail et numéro de téléphone',
          'Toutes les données nécessaires à la création du compte client, au passage de commandes, mais aussi à la facturation et la livraison des commandes passées' => 'Toutes les données nécessaires à la création du compte client, au passage de commandes, mais aussi à la facturation et la livraison des commandes passées',
        ),
        'default_value' => false,
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_629f1ba310120',
        'label' => 'Délai de conservation des données',
        'name' => 'conservation_des_donnees',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '24 mois',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_629f141d3e037',
        'label' => 'Tribunaux compétents',
        'name' => 'tribunaux',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Bordeaux',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page',
          'operator' => '==',
          'value' => '3',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
  
  endif;		
  // END - ACF